
services:
  api:
    container_name: lawyersystem-api-dev
    build:
      context: .
      dockerfile: lawyerSystem.api/Dockerfile
      target: build


    command: dotnet watch run --urls "http://+:8080" --non-interactive
    ports:
      - "5001:8080"
    volumes:
      - ./lawyerSystem.api:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres_db;Port=5432;Database=lawyersystem_db;User Id=postgres;Password=postgres;
      - JwtSettings__SecretKey=senha123
    depends_on:
      - postgres_db

  postgres_db:
    container_name: lawyersystem-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lawyersystem_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: